language: python
python:
  - "2.7"
install:
  - pip install ansible
script:
  - echo "localhost" > hosts
  - ansible-playbook --syntax-check -i hosts .travis.d/role.yml
  - ansible-playbook -i hosts .travis.d/role.yml --connection=local -vvv
